# this file is only used for GitHub
# it is not related to your Kafka Streams learning
sudo: required

services:
  - docker

addons:
  hosts:
    - kafka1
    - kafka2
    - kafka3
    - zoo1
    - zoo2
    - zoo3
    - kafka-schema-registry
    - kafka-schema-registry-ui
    - kafka-rest-proxy
    - kafka-topics-ui
    - kafka-connect-ui
    - zoonavigator-web
    - zoonavigator-api
    
  # install the kafka binaries
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] https://packages.confluent.io/deb/4.1 stable main'
        key_url: 'https://packages.confluent.io/deb/4.1/archive.key'
    packages:
      - confluent-platform-oss-2.11
      - kafkacat

script:
# test the java components
- ./test.sh zk-single-kafka-single.yml 2
- ./test.sh zk-multiple-kafka-single.yml 4
- ./test.sh zk-single-kafka-multiple.yml 4
- ./test.sh zk-multiple-kafka-multiple.yml 6
- ./test.sh full-stack.yml 10