# this file is only used for GitHub
# it is not related to your Kafka Streams learning
sudo: required

env:
  - DOCKER_HOST_IP=127.0.0.1
  # - DOCKER_HOST_IP=192.168.99.100

services:
  - docker

addons:
  # install the kafka binaries
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] https://packages.confluent.io/deb/4.1 stable main'
        key_url: 'https://packages.confluent.io/deb/4.1/archive.key'
    packages:
      - confluent-platform-oss-2.11
      # - kafkacat

script:
# test the java components
- ./test.sh zk-single-kafka-single.yml 2
- ./test.sh zk-multiple-kafka-single.yml 4
- ./test.sh zk-single-kafka-multiple.yml 4
- ./test.sh zk-multiple-kafka-multiple.yml 6
- ./test.sh full-stack.yml 10